/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproyecto3;

/**
 *
 * @author Juan Camilo
 */
public class ventnomina extends javax.swing.JFrame {

    /**
     * Creates new form ventnomina
     */
    public ventnomina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        panelbotones = new javax.swing.JPanel();
        botoncalculo = new javax.swing.JButton();
        botonreporte = new javax.swing.JButton();
        botonempleados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        nombre6 = new javax.swing.JLabel();
        nombre4 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        nombre7 = new javax.swing.JLabel();
        nombre5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setLayout(null);

        panelbotones.setBackground(new java.awt.Color(204, 255, 255));
        panelbotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botoncalculo.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        botoncalculo.setText("Calculo Nomina");
        botoncalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncalculoActionPerformed(evt);
            }
        });

        botonreporte.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        botonreporte.setText("Reporte nomina");
        botonreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonreporteActionPerformed(evt);
            }
        });

        botonempleados.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        botonempleados.setText("Empleados");
        botonempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonempleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbotonesLayout = new javax.swing.GroupLayout(panelbotones);
        panelbotones.setLayout(panelbotonesLayout);
        panelbotonesLayout.setHorizontalGroup(
            panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbotonesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(botonempleados)
                .addGap(52, 52, 52)
                .addComponent(botoncalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonreporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        panelbotonesLayout.setVerticalGroup(
            panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbotonesLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoncalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        Panel1.add(panelbotones);
        panelbotones.setBounds(20, 120, 780, 150);

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mini Proyecto 3");
        Panel1.add(jLabel1);
        jLabel1.setBounds(80, 20, 620, 80);

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproyecto3/imagenes/584c695d6e7d5809d2fa6362.png"))); // NOI18N
        Panel1.add(img1);
        img1.setBounds(330, 390, 130, 200);

        nombre1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre1.setText("2262525");
        Panel1.add(nombre1);
        nombre1.setBounds(590, 340, 170, 50);

        nombre6.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        nombre6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre6.setText("Santiago PEÑA");
        Panel1.add(nombre6);
        nombre6.setBounds(590, 290, 170, 50);

        nombre4.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        nombre4.setForeground(new java.awt.Color(255, 51, 51));
        nombre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre4.setText("JUIAN cAMILO tRIANA");
        Panel1.add(nombre4);
        nombre4.setBounds(290, 280, 220, 70);

        img3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproyecto3/imagenes/archivo.png"))); // NOI18N
        Panel1.add(img3);
        img3.setBounds(0, 400, 230, 200);

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproyecto3/imagenes/sisas.png"))); // NOI18N
        Panel1.add(img2);
        img2.setBounds(600, 390, 220, 220);

        nombre2.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        nombre2.setForeground(new java.awt.Color(204, 204, 0));
        nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre2.setText("2362521");
        Panel1.add(nombre2);
        nombre2.setBounds(20, 340, 170, 50);

        nombre7.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        nombre7.setForeground(new java.awt.Color(204, 204, 0));
        nombre7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre7.setText("Kevin Galeano");
        Panel1.add(nombre7);
        nombre7.setBounds(20, 290, 170, 50);

        nombre5.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        nombre5.setForeground(new java.awt.Color(255, 51, 51));
        nombre5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre5.setText("2362307");
        Panel1.add(nombre5);
        nombre5.setBounds(290, 320, 220, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonempleadosActionPerformed
        ventempleados vent= new ventempleados();
        vent.setTitle("Empleados");
        vent.setLocation(400,300);
        vent.setSize(930,622);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonempleadosActionPerformed

    private void botoncalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncalculoActionPerformed
        ventcalcularnomina vent= new ventcalcularnomina();
        vent.setTitle("Calculo");
        vent.setLocation(400,300);
        vent.setSize(1168, 800);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botoncalculoActionPerformed

    private void botonreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonreporteActionPerformed
        ventconsultarnomina vent= new ventconsultarnomina();
        vent.setTitle("Reporte");
        vent.setLocation(400,300);
        vent.setSize(1168, 800);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonreporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventnomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventnomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventnomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventnomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventnomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton botoncalculo;
    private javax.swing.JButton botonempleados;
    private javax.swing.JButton botonreporte;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre4;
    private javax.swing.JLabel nombre5;
    private javax.swing.JLabel nombre6;
    private javax.swing.JLabel nombre7;
    private javax.swing.JPanel panelbotones;
    // End of variables declaration//GEN-END:variables
}
